### PR TITLE
Enable examples flag

### PR DESCRIPTION
**Pull request by DaManDOH**
Issue #6 — Added logic to include OpenAPI examples in generated PDF.

### CODE REVIEW

**Comment by mrin9** [comment]
Thanks for the PR,
and its nice that you update the API documentation and put up an example to show its working !!!

There are couple of issues with it 
- It assumes that examples will be always in JSON
- It wont auto-generate the examples
- It wont indent the JSON 

here is how it looks 
Screen Shot 2020-07-26 at 10 34 31 AM

But having said that, I think we can start small and improve upon it later. 

I will accept the PR now and will support. we will add indentation to it later

**Comment by DaManDOH** [comment]
> Thanks for the PR,
> and its nice that you update the API documentation and put up an example to show its working !!!

Thanks! Lacking documentation is always a problem.
 
> There are couple of issues with it
> 
> * It assumes that examples will be always in JSON

The JSON stringifier _should_ treat any other language as a basic JSON string, but I will admit I did not test anything beyond JSON and basic strings.

> * It wont auto-generate the examples

As the request and response example(s) properties are static fields in OpenAPI's specification, shouldn't the population of those fields be the responsibility of the OpenAPI documentation generator? In other words: shouldn't the subject API's JSON/YAML file already have the generated examples before it's passed to RapiPdf?

> * It wont indent the JSON

Yea, CSS is not my strong suit. 😅

**Comment by gmmarc** [comment]
@mrin9 this PR works great, but it's not included in the latest release v2.2.1. Thus, you need to build from source code to benefit from this PR (installing with yarn won't work). 

It would be great if you could deploy a new release with the latest updates 👍 

Also sharing in case someone runs into the same issue—It took me more time than I want to admit to figure it out 😅

**Comment by da-cheng293** [comment]
if possible, plz include the lastest change in the master. Thanks

**Pull request merged**
